#pragma config(Motor,  port2,           shooterR1,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           shooterR2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           shooterR3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           shooterL1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           shooterL2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           shooterL3,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task intake(){
 while (true){
		if (vexRT[Btn6U] == 1){
			motor[shooterR1] = 120;
			motor[shooterR2] = 120;
			motor[shooterR3] = 120;
			motor[shooterL1] = 120;
			motor[shooterL2] = 120;
			motor[shooterL3] = 120;
			}else if (vexRT[Btn6D] == 1){
			motor[shooterR1] = -120;
			motor[shooterR2] = -120;
			motor[shooterR3] = -120;
			motor[shooterL1] = -120;
			motor[shooterL2] = -120;
			motor[shooterL3] = -120;
			}else{
			motor[shooterR1] 	= 0;
			motor[shooterR2]	= 0;
			motor[shooterR3] 	= 0;
			motor[shooterL1] 	= 0;
			motor[shooterL2] 	= 0;
			motor[shooterL3] 	= 0;
		}
	}
}

task intakeR(){
 while (true){
		if (vexRT[Btn8U] == 1){
			motor[shooterR1] = 120;
			motor[shooterR2]=  120;
			motor[shooterR3] = 120;
			motor[shooterL1] = 0;
			motor[shooterL2] = 0;
			motor[shooterL3] = 0;
			}else if (vexRT[Btn8D] == 1){
			motor[shooterR1] = -120;
			motor[shooterR2]=  -120;
			motor[shooterR3] = -120;
			motor[shooterL1] = 0;
			motor[shooterL2] = 0;
			motor[shooterL3] = 0;
			}else{
			motor[shooterR1] 	= 0;
			motor[shooterR2]	= 0;
			motor[shooterR3] 	= 0;
			motor[shooterL1] 	= 0;
			motor[shooterL2] 	= 0;
			motor[shooterL3] 	= 0;
		}
	}
}
task intakeL(){
 while (true){
		if (vexRT[Btn7U] == 1){
			motor[shooterR1] = 0;
			motor[shooterR2]=  0;
			motor[shooterR3] = 0;
			motor[shooterL1] = 120;
			motor[shooterL2] = 120;
			motor[shooterL3] = 120;
			}else if (vexRT[Btn7D] == 1){
			motor[shooterR1] = 0;
			motor[shooterR2] = 0;
			motor[shooterR3] = 0;
			motor[shooterL1] = -120;
			motor[shooterL2] = -120;
			motor[shooterL3] = -120;
			}else{
			motor[shooterR1] 	= 0;
			motor[shooterR2]	= 0;
			motor[shooterR3] 	= 0;
			motor[shooterL1] 	= 0;
			motor[shooterL2] 	= 0;
			motor[shooterL3] 	= 0;
		}
	}
}


task main()
{
	startTask(intake);
	startTask(intakeR);
	startTask(intakeL);
	while(true){
		wait1Msec(1);
	}


}
