#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           MiddleRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RearRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           MiddleLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RearLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////
task main()
{
	while (true){
		if (vexRT[Btn5D] == 1){
			motor[FrontLeft] = 60;
			motor[MiddleLeft]= 60;
			motor[RearLeft] = 60;

			motor[FrontRight] = 60;
			motor[MiddleRight]= 60;
			motor[RearRight] = 60;
			}else if (vexRT[Btn5U] == 1){
			motor[FrontLeft] = -60;
			motor[MiddleLeft]= -60;
			motor[RearLeft] = -60;

			motor[FrontRight] = -60;
			motor[MiddleRight]= -60;
			motor[RearRight] = -60;
			}else{
			motor[FrontLeft] = 0;
			motor[MiddleLeft]= 0;
			motor[RearLeft] = 0;

			motor[FrontRight] = 0;
			motor[MiddleRight]= 0;
			motor[RearRight] = 0;
		}
	}

}
