#pragma config(Motor,  port2,           back,          tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           front,         tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           left,          tmotorVex393_MC29, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor[right] = vexRT[Ch2];
		motor[left] = vexRT[Ch2];
		motor[front] = vexRT[Ch3];
		motor[back] = vexRT[Ch3];
		wait1Msec(10);
	}

}
