#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  topOfArm,       sensorTouch)
#pragma config(Sensor, dgtl6,  bottomOfArm,    sensorTouch)
#pragma config(Motor,  port1,           in1,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           MiddleRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RearRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           in2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           in3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           MiddleLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RearLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          in4,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

int requestedLeftSpeed 	= 0;
int requestedRightSpeed = 0;
short speedIncrement 		= 1;
short stallSpeed 				= 10;
int maxSpeed 						= 30;
int leften;
int righten;
int distance = 2550;
int intakepower = 100;


//////////////////////////////////////////////////////////////////////////////////////////
int isDecelerating (int requested, int current){
	if (abs(requested)< abs(current) && (requested * current) > 0 || (requested * current) < 0)
	{
		return 1;
		}else{
		return 0;
	}
}
//////////////////////////////////////////////////////////////////////////////////////////
int max (short x , short y )
{
	return x < y ? y : x;
}
//////////////////////////////////////////////////////////////////////////////////////////
task drivefoward(){
	while(true){
		while(leften <distance || righten <distance){
			requestedLeftSpeed = 100;
			requestedRightSpeed = 100;
	 	}
	 	requestedLeftSpeed = 0;
	 	requestedRightSpeed = 0;
	}
}
task intake(){
 while (true){
		if (vexRT[Btn6U] == 1 ){
			motor[in1] = intakepower;
			motor[in2]= intakepower;
			motor[in3] = intakepower;
			motor[in4] = intakepower;
			}else if (vexRT[Btn6D] == 1){
			motor[in1] = -1 * intakepower;
			motor[in2]= -1 * intakepower;
			motor[in3] = -1 * intakepower;
			motor[in4] = -1 * intakepower;
			}else{
			motor[in1] = 0;
			motor[in2]= 0;
			motor[in3] = 0;
			motor[in4] = 0;
		}
	}
}

///////////////////////////////////////////////////////////////////////////////////
task accelerator()
{
	int currentRightSpeed 	= 0;
	int currentLeftSpeed 	= 0;
	while(true){

		if (requestedLeftSpeed != currentLeftSpeed)
		{


			short Increment = speedIncrement;

			if (isDecelerating (requestedLeftSpeed, currentLeftSpeed) == 1){
				Increment = 20;

			}


			//Eliminate overshoot
			else if (abs(requestedLeftSpeed - currentLeftSpeed) < Increment){
				Increment = abs(requestedLeftSpeed - currentLeftSpeed);
			}

			if (requestedLeftSpeed > currentLeftSpeed) {
				currentLeftSpeed = currentLeftSpeed + Increment;
				}else {
				currentLeftSpeed = currentLeftSpeed - Increment;
			}
			motor[FrontLeft] = -currentLeftSpeed;
			motor[MiddleLeft]= -currentLeftSpeed;
			motor[RearLeft] = -currentLeftSpeed;

		}
		if (requestedRightSpeed != currentRightSpeed)
		{


			short Increment = speedIncrement;

			if (isDecelerating (requestedRightSpeed, currentRightSpeed) == 1){
				Increment = 15;
			}

			else if (abs(requestedRightSpeed - currentRightSpeed) < Increment) {
				Increment = abs(requestedRightSpeed - currentRightSpeed);
			}

			if (requestedRightSpeed > currentRightSpeed) {
				currentRightSpeed = currentRightSpeed + Increment;
				}else {
				currentRightSpeed = currentRightSpeed - Increment;
			}
			motor[FrontRight] = currentRightSpeed;
			motor[MiddleRight]= currentRightSpeed;
			motor[RearRight] = currentRightSpeed;

		}
		wait1Msec(10);

	}
}
//////////////////////////////////////////////////////////////////////////////////////////
task joystickMonitor()
{
	while(true)
	{
		if (vexRT[Btn5D] ==1)
		{
			maxSpeed 		= 30;
			speedIncrement	= 1;
		}
		else
		{
			maxSpeed		= 127;
			speedIncrement	 = 5;
		}


		float scale 		= (float)maxSpeed / 127.0;
		requestedLeftSpeed 	= (short)(float)((-1 * vexRT[Ch3]) - vexRT[Ch4])*scale;
		requestedRightSpeed	= (short)(float)((-1 * vexRT[Ch3]) + vexRT[Ch4])*scale;
		short maxLR;
		float f;



		if (abs(requestedLeftSpeed)< stallSpeed *scale)
		{
			requestedLeftSpeed 	= 0;
			speedIncrement		= 20;
		}
		if (abs(requestedRightSpeed)< stallSpeed *scale)
		{
			requestedRightSpeed = 0;
			speedIncrement 		= 20;
		}
		maxLR = max( abs (requestedLeftSpeed), abs (requestedRightSpeed));

		if (maxLR > maxSpeed)
		{
			if(abs(requestedLeftSpeed) > abs (requestedRightSpeed))
				f = abs((float)maxSpeed/requestedLeftSpeed);
			else
				f = abs((float)maxSpeed/requestedRightSpeed);
			requestedLeftSpeed = requestedLeftSpeed * f;
			requestedRightSpeed = requestedRightSpeed * f;
		}
		wait1Msec(10);
	}
}
//////////////////////////////////////////////////////////////////////////////////////////
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	leften 		= -1 * SensorValue[leftEncoder];
	righten 	= SensorValue[rightEncoder];
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................
	startTask (drivefoward);
	startTask (accelerator);
  // Remove this function call once you have "real" code.

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	startTask(accelerator);
	startTask (joystickMonitor);
	startTask(intake);
  while (true)
  {
  	wait1Msec(10);
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.

  }
}
//////////////////////////////////////////////////////////////////////////////////////////
