#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           MiddleRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RearRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           FrontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           MiddleLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RearLeft,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int requestedLeftSpeed 	= 0;
int requestedRightSpeed = 0;
short speedIncrement 		= 1;
short stallSpeed 				= 20;
int maxSpeed 						= 30;
/////////////////////////////////////////////////////////////////////////////////////////
int isDecelerating (int requested, int current){
	if (abs(requested)< abs(current) && (requested * current) > 0 || (requested * current) < 0)
	{
		return 1;
		}else{
		return 0;
	}
}
//////////////////////////////////////////////////////////////////////////////////////////
int max (short x , short y )
{
	int vithuran = 0.25;
	return x < y ? y : x;
}
//////////////////////////////////////////////////////////////////////////////////////////
task accelerator()
{
	int currentRightSpeed 	= 0;
	int currentLeftSpeed 	= 0;
	while(true){
		while (vexRT[Btn6U] == 0)
		{
			if (requestedLeftSpeed != currentLeftSpeed)
			{
				short Increment = speedIncrement;
				if (isDecelerating (requestedLeftSpeed, currentLeftSpeed) == 1){
					Increment = 20;
				}
				else if (abs(requestedLeftSpeed - currentLeftSpeed) < Increment){
					Increment = abs(requestedLeftSpeed - currentLeftSpeed);
				}
				if (requestedLeftSpeed > currentLeftSpeed) {
					currentLeftSpeed = currentLeftSpeed + Increment;
					}else {
					currentLeftSpeed = currentLeftSpeed - Increment;
				}
				motor[FrontLeft] = -currentLeftSpeed;
				motor[MiddleLeft]= -currentLeftSpeed;
				motor[RearLeft] = -currentLeftSpeed;
			}
			if (requestedRightSpeed != currentRightSpeed)
			{
				short Increment = speedIncrement;
				if (isDecelerating (requestedRightSpeed, currentRightSpeed) == 1){
					Increment = 15;
				}
				else if (abs(requestedRightSpeed - currentRightSpeed) < Increment) {
					Increment = abs(requestedRightSpeed - currentRightSpeed);
				}
				if (requestedRightSpeed > currentRightSpeed) {
					currentRightSpeed = currentRightSpeed + Increment;
					}else {
					currentRightSpeed = currentRightSpeed - Increment;
				}
				motor[FrontRight] = currentRightSpeed;
				motor[MiddleRight]= currentRightSpeed;
				motor[RearRight] = currentRightSpeed;
			}
			wait1Msec(10);
		}
	}
}
//////////////////////////////////////////////////////////////////////////////////////////
task joystickMonitorTank()
{
	while(true)
	{
		if (vexRT[Btn5D] ==1)
		{
			maxSpeed 		= 30;
			speedIncrement	= 1;
		}
		else
		{
			maxSpeed		= 127;
			speedIncrement	 = 5;
		}
		float scale 		= (float)maxSpeed / 127.0;
		requestedLeftSpeed 	= (short)(float)((-1 * vexRT[Ch3]) + vexRT[Ch4])*scale;
		requestedRightSpeed	= (short)(float)((-1 * vexRT[Ch3]) - vexRT[Ch4])*scale;
		short maxLR;
		float f;
		if (abs(requestedLeftSpeed)< stallSpeed *scale)
		{
			requestedLeftSpeed 	= 0;
			speedIncrement		= 20;
		}
		if (abs(requestedRightSpeed)< stallSpeed *scale)
		{
			requestedRightSpeed = 0;
			speedIncrement 		= 20;
		}
		maxLR = max( abs (requestedLeftSpeed), abs (requestedRightSpeed));
		if (maxLR > maxSpeed)
		{
			if(abs(requestedLeftSpeed) > abs (requestedRightSpeed))
				f = abs((float)maxSpeed/requestedLeftSpeed);
			else
				f = abs((float)maxSpeed/requestedRightSpeed);
			requestedLeftSpeed = requestedLeftSpeed * f;
			requestedRightSpeed = requestedRightSpeed * f;
		}
		wait1Msec(10);
	}
}
//////////////////////////////////////////////////////////////////////////////////////////
task joystickMonitorArcade()
{
	while(true)
	{
		if (vexRT[Btn5D] ==1)
		{
			maxSpeed 		= 30;
			speedIncrement	= 1;
		}
		else
		{
			maxSpeed		= 127;
			speedIncrement	 = 5;
		}
		float scale 		= (float)maxSpeed / 127.0;
		requestedLeftSpeed 	= (short)(float)((-1 * vexRT[Ch3]))*scale;
		requestedRightSpeed	= (short)(float)((-1 * vexRT[Ch2]))*scale;
		short maxLR;
		float f;
		if (abs(requestedLeftSpeed)< stallSpeed *scale)
		{
			requestedLeftSpeed 	= 0;
			speedIncrement		= 20;
		}
		if (abs(requestedRightSpeed)< stallSpeed *scale)
		{
			requestedRightSpeed = 0;
			speedIncrement 		= 20;
		}
		maxLR = max( abs (requestedLeftSpeed), abs (requestedRightSpeed));
		if (maxLR > maxSpeed)
		{
			if(abs(requestedLeftSpeed) > abs (requestedRightSpeed))
				f = abs((float)maxSpeed/requestedLeftSpeed);
			else
				f = abs((float)maxSpeed/requestedRightSpeed);
			requestedLeftSpeed = requestedLeftSpeed * f;
			requestedRightSpeed = requestedRightSpeed * f;
		}
		wait1Msec(10);
	}
}
//////////////////////////////////////////////////////////////////////////////////////////
task main(){
	startTask(accelerator);
	startTask (joystickMonitorTank);
	while(true){
		wait1Msec(10);
	}
}
